twig:
    default_path: '%kernel.project_dir%/templates'
    exception_controller: null
framework:
    error_controller: App\Controller\ExceptionController::exception

when@test:
    twig:
        strict_variables: true
